### PR TITLE
Add getRTCStatsReport method to local and remote track classes

### PR DESCRIPTION
**Pull request by tab1293**

### CODE REVIEW

**Comment by lukasIO** [comment]
hi @tab1293 , 
thanks for the PR! 

We expose `getSenderStats` and `getReceiverStats` already with a stripped down version of RTCStats. 
Are you primarily interested in some specific stats that these APIs currently do not expose or is the main motivation for this PR to have a way to retrieve _all_ stats ?

**Comment by tab1293** [comment]
@lukasIO hey sorry for the late response here. But yes the primary motivation of the PR is to have a way to retrieve all stats.

**Comment by lukasIO** [comment]
makes sense, I think that's a good addition. Could you sign the CLA, so that I can merge this in ?

**Comment by tab1293** [comment]
@lukasIO sorry CLA is signed now!

**Review by lukasIO — APPROVED** [review]

**Pull request merged**
