### PR TITLE
Improvements to the sample app

### PR DESCRIPTION
**Pull request by davidzhao**
* Ability to control adaptive video
* Better looking video tiles
* Displays video resolution in bar

Screen Shot 2021-12-14 at 1 04 48 AM

### CODE REVIEW

**Review by boks1971 — APPROVED** [review]
Nice!!! Haven't read it throughly, but will be using it and will look for any oddities.

Feature request - can we have a UI option to disable to the auto-on/off of encodings in Simulcast track?

**Review by hiroshihorie — APPROVED** [review]
Nice!

**Comment by davidzhao** [comment]
> Feature request - can we have a UI option to disable to the auto-on/off of encodings in Simulcast track?

Sure thing!

**Comment by hiroshihorie** [comment]
...but you should turn on the lights, not good for your eyes haha 😅

**Comment by davidzhao** [comment]
> ...but you should turn on the lights, not good for your eyes haha 😅

LOL, got me.

**Comment by davidzhao** [comment]
@boks1971 I added this as a `connect` option: `expDisableLayerPause`. Decided against adding it to the sample app to avoid any confusion to users.

**Comment by boks1971** [comment]
> @boks1971 I added this as a `connect` option: `expDisableLayerPause`. Decided against adding it to the sample app to avoid any confusion to users.

Sounds good @davidzhao . Thank you!

**Pull request merged**
