### PR TITLE
Room.isRecording to surface if the room is being recorded

### PR DESCRIPTION
**Pull request by davidzhao**

### CODE REVIEW

**Review by lukasIO — APPROVED** [review]
lgtm! just wondering if we'd want to surface this as an event for convenience?

**Comment by davidzhao** [comment]
> lgtm! just wondering if we additionally want to surface this as an event for convenience?

that's true.. let's think on that for a bit. thinking that it might be easier to think about to have a single event that indicates attributes about the room have changed.. rather than one event for each attribute.

**Comment by lukasIO** [comment]
what other room attributes do you have in mind?
If there aren't too many, I think a granular event for recording could still make sense

**Comment by lukasIO** [comment]
@davidzhao does the additional event look ok to you?

**Review by davidzhao — COMMENTED** [review]
This looks good. Thanks @lukasIO

**Pull request merged**
