### PR TITLE
Add vp9 support for E2EE

### PR DESCRIPTION
**Pull request by lukasIO**
Unfortunately av1 fails with `TypeError: Destination stream closed` when trying to decode frames. This needs further investigation. 
Until then, VP9 addition is nice, too!

~~Caveats: this is currently only secure if `backupCodec: undefined` is specified. Backup codecs are currently sent unencrypted, which is definitely unexpected. ~~
^ backup codecs are currently disabled in general when e2ee is enabled

### CODE REVIEW

**Comment by lukasIO** [comment]
closing for now due to the backupCodec complications

**Comment by Stogas** [comment]
@lukasIO 

Could you elaborate a little bit?

I'd still consider this open, as VP9 support is still wanted and missing.

**Comment by lukasIO** [comment]
hi @Stogas, 

encryption support for backup codecs is missing, which would be needed to ensure that also clients that don't support vp9 would be able to receive the media stream. 

I can reopen the issue, but there's currently no ETA for encryption support of backup codecs

**Comment by davidzhao** [comment]
We should disable backupCodec when e2ee is used. since vp9 is supported everywhere, I think the impact of that should be fairly minimal

**Comment by lukasIO** [comment]
> We should disable backupCodec when e2ee is used.

That's what we do already today. 
I'll update this PR in order to merge it in

**Review by davidzhao — APPROVED** [review]
awesome!

**Pull request merged**
