### PR TITLE
added option to update token

### PR DESCRIPTION
**Pull request by jibon57**
Added option to update token. In long run meeting sometime token got expire & if client need to run reconnect for any reason that time it failed. Now it will be possible to update token periodically.

### CODE REVIEW

**Comment by davidzhao** [comment]
hey @jibon57 this is an excellent fix/idea.

I think we can handle this on the server side automatically without you having to regenerate/set token. What do you think about the following policy? If a participant is currently/recently connected, then we shall allow the expired token to be used.

This way all clients could continue to work seamlessly.

**Comment by jibon57** [comment]
@davidzhao thank you. How you are planning to differentiate if that user joined recently? If user is smart enough then can reuse same token again & again. In our new system (which will be open source :-D) we have set validity of token for 10 minutes & renew using backend server periodically every 8 minutes which will require to send valid token before expire to renew. So, if meeting ended there have very less chances to reuse same token.

**Comment by davidzhao** [comment]
Since it's a real time system, we know exactly when users are connected and have left. The idea is to have only a <1m window where users could re-connect after leaving.

**Comment by jibon57** [comment]
This will be perfect!

**Comment by davidzhao** [comment]
Should be handled by https://github.com/livekit/client-sdk-js/pull/131. The server will issue new, valid tokens to the client

**Pull request closed without merging**
