### PR TITLE
add screenshareaudio track source

### PR DESCRIPTION
**Pull request by lukasIO**
Right now screen share audio has an "unknown" source type set. 
I found myself needing to know specifically if it is audio from a screen share, thus this PR.

### CODE REVIEW

**Comment by davidzhao** [comment]
> Hm, thinking about it more, it might also suffice to just set the source as `ScreenShare` also for screen audio and differentiate between screen video and audio by looking at `Track.Kind`.

Yeah I think that's true.. though we'd need our helper functions to perform filtering correctly. I think that's better technically.. because the source of the stream is from the screen share.

**Comment by lukasIO** [comment]
@davidzhao are there any other helper functions apart from `getTrack` that need to adjust their filtering for screenshare audio?

**Comment by davidzhao** [comment]
hey @lukasIO I'm thinking about this a bit more. It does seem like this could be kind of confusing.. It was nice before to have a one to one relationship between TrackSource -> Track

now this introduces another dimension to consider... So my apologies.. but it's better to add a unique source for this. I can add this to the protocol layer so clients could get the generated protobufs.

**Comment by lukasIO** [comment]
I had the same feeling when writing it out... 
Would be great if you could add it in the protocol, I'll adjust the naming here (or feel free to do it yourself) if you want to change the event name.

**Comment by davidzhao** [comment]
@lukasIO protobufs and helper methods have been added.

**Review by davidzhao — APPROVED** [review]
lg!

**Pull request merged**
