### PR TITLE
Stricter tsconfig

### PR DESCRIPTION
**Pull request by hn8**
Enable noUnusedLocals

### CODE REVIEW

**Comment by davidzhao** [comment]
hey Hann, what's the benefit of `importsNotUsedAsValues` ?

**Comment by hn8** [comment]
@davidzhao It prevents accidentally non-type import (increase build size). But since LiveKit JS only has 1 build output, it is only for explicit "documentation" purpose. Will revert that commit if it is not worth extra check.

**Comment by hn8** [comment]
@davidzhao I reverted noImplicitReturns and importsNotUsedAsValues to minimize changes. Keep noUnusedLocals check which is similar to Go.

**Comment by davidzhao** [comment]
thanks! this looks good.

**Pull request merged**
