### PR TITLE
Added new RTCEngine event to signal when the publisher/subscriber transports are created

### PR DESCRIPTION
**Pull request by onel**
As per the discussion in slack, I've create a new event that will be fired on `RTCEngine` that will signal when the transports are created.

### CODE REVIEW

**Comment by boks1971** [comment]
Slack thread - https://livekit-users.slack.com/archives/C01KVTJH6BX/p1644435469140019

**Review by lukasIO — COMMENTED** [review]
hey @onel, this looks good.
could you just fix the lint issue and rebase with the latest changes in `main` ?
we just introduced typed callbacks for events, so there would have to be a typed callback for the `EngineEvent.TransportsCreated` as well. 
Relevant code at https://github.com/livekit/client-sdk-js/blob/main/src/room/RTCEngine.ts#L611-L626

**Comment by onel** [comment]
Thanks for the feedback, @lukasIO 
Made the changes.

**Comment by onel** [comment]
@davidzhao Ohh, sure thing. Signed

**Comment by davidzhao** [comment]
thank you! merging the PR now.

**Pull request merged**
